---
title: "Week 02 assignment"
author: "Lulu"
date: "2026-03-04"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(dplyr)
  library(ggplot2)
})
```
```{r}
ah <- AnnotationHub()
ah

# 1.1 Mouse EnsDb v102, GRCm38
q_ensdb <- query(ah, c("EnsDb", "Mus musculus", "102", "GRCm38"))
q_ensdb
edb <- ah[[ rev(q_ensdb$ah_id)[1] ]]
edb

# 1.2 Mouse dna_sm TwoBit, GRCm38
q_mm_2bit <- query(ah, c("Mus musculus", "GRCm38", "TwoBit", "dna_sm"))
q_mm_2bit
mm_2bit <- ah[[ rev(q_mm_2bit$ah_id)[1] ]]
mm_2bit

# 1.3 Drosophila dna_sm TwoBit, BDGP6
q_dm_2bit <- query(ah, c("Drosophila melanogaster", "BDGP6", "TwoBit", "dna_sm"))
q_dm_2bit
dm_2bit <- ah[[ rev(q_dm_2bit$ah_id)[1] ]]
dm_2bit

## 1.2 Mouse genome sequence (dna_sm) TwoBit/2bit for GRCm38
q_mm_2bit <- query(ah, c("Mus musculus", "GRCm38", "TwoBit", "dna_sm"))
q_mm_2bit
mm_2bit <- q_mm_2bit[[1]]
mm_2bit

## 1.3 Drosophila melanogaster genome sequence (dna_sm) TwoBit/2bit for BDGP6
q_dm_2bit <- query(ah, c("Drosophila melanogaster", "BDGP6", "TwoBit", "dna_sm"))
q_dm_2bit
dm_2bit <- q_dm_2bit[[1]]
dm_2bit
```
```{r}
# Filter protein-coding genes
# In EnsDb, we can query genes with gene_biotype == "protein_coding"
pc_genes <- genes(edb, filter=GeneBiotypeFilter("protein_coding"),
                  columns=c("gene_id","gene_name","gene_biotype"))

# Count unique Ensembl gene IDs and unique gene symbols (gene_name)
n_gene_ids <- length(unique(mcols(pc_genes)$gene_id))
n_gene_symbols <- length(unique(mcols(pc_genes)$gene_name))

n_gene_ids
n_gene_symbols
```
```{r}
# Get protein-coding transcripts (with tx_id/tx_name) to define set
pc_tx <- transcripts(edb,
                     filter=GeneBiotypeFilter("protein_coding"),
                     columns=c("tx_id","tx_name","gene_id","gene_name","tx_biotype"))

# Extract exons linked to transcripts (EnsDb keeps exon->tx mapping)
pc_exons <- exons(edb,
                  filter=GeneBiotypeFilter("protein_coding"),
                  columns=c("exon_id","tx_id","tx_name"))

# Compute spliced length per transcript by summing exon widths
df <- as.data.frame(mcols(pc_exons))
df$exon_width <- width(pc_exons)

ex_df <- df %>%
  group_by(tx_id, tx_name) %>%
  summarise(spliced_length = sum(exon_width), .groups = "drop")
```
```{r}
ggplot(ex_df, aes(x = spliced_length)) +
  geom_histogram(bins = 60) +
  scale_x_log10() +
  labs(
    title = "Distribution of spliced transcript length (protein-coding, mouse GRCm38)",
    x = "Spliced length (sum of exon widths) [log10 scale]",
    y = "Number of transcripts"
  )
```

sessionInfo()